### ISSUE TITLE
Update markup of templates to Bootstrap 4

### ISSUE THREAD

**Issue by santonelli** [plone/plone.batching#25]
Due to #2967 we have to update the markup of the templates listed below. 

- [x] plone.batching.batchnavigation.pt

Feel free to add missing templates here. See also #3061 for further details. Check overrides in [plonetheme.tokyo](https://github.com/collective/plonetheme.tokyo) for already existing updated templates.

**Comment by agitator** [comment]
fixed as override in barceloneta
