### ISSUE TITLE
Incorrect behavior using orphan

### ISSUE THREAD

**Issue by keul** [plone/plone.batching#9]
I'm manually using batching on a non-plone sequence and I'm having issue with latest 1.0.5 version (version 1.0.4 with the configuration belowe raise an error I think you fixed in the 1.0.5).

This is the batch call:

```
Batch(self._rows, 10, start=self.b_start, end=self.b_start+bsize, orphan=1, overlap=0, pagerange=7)
```

`bsize` is 10

My `self._rows` is a 11-long sequence.

The effect: in the template the orphan parameter seems partially ignored: instead of seeing a single page of 11 elements (10+1 orphan) I see 10 elements and a link to page 2.

Going to page two will show the 11th element but the navigation UI will still show only a "[1]" (not linkable) and no "previous page" link.

**Comment by cekk** [comment]
I think that this is an issue also for Plone folder_listing view.
If in a Plone 5.1.4 clean installation i create 21 elements into a folder, the view shows me 20 elements and creates the navigation element with only one page and two empty pagination links.

**Comment by mauritsvanrees** [comment]
Confirmed in Plone 5.1.4, also in coredev.

On Plone 4.3 (plone.batching 1.0.8) all is fine, at least when testing with a Collection that shows twenty results per page and has 21 results. It simply shows 1 and 2 as batching pages.

On Plone 5.1, with standard folder listing, I literally see `... 1 ...` as batching.
That is with latest plone.batching 1.1.4. Going back to 1.1.0 gives the same problem. Going to 1.0.8 gives the old batching layout with correct links.

I will check.
